import 'dart:convert';

import 'package:equatable/equatable.dart';

/// Review status for a draft card.
enum DraftReviewStatus {
  /// Not yet reviewed.
  pending,

  /// Approved as-is.
  approved,

  /// Edited and approved.
  edited,

  /// Rejected (will not be imported).
  rejected,
}

extension DraftReviewStatusExtension on DraftReviewStatus {
  String get displayName {
    switch (this) {
      case DraftReviewStatus.pending:
        return 'Pendente';
      case DraftReviewStatus.approved:
        return 'Aprovado';
      case DraftReviewStatus.edited:
        return 'Editado';
      case DraftReviewStatus.rejected:
        return 'Rejeitado';
    }
  }

  String get value {
    switch (this) {
      case DraftReviewStatus.pending:
        return 'pending';
      case DraftReviewStatus.approved:
        return 'approved';
      case DraftReviewStatus.edited:
        return 'edited';
      case DraftReviewStatus.rejected:
        return 'rejected';
    }
  }

  static DraftReviewStatus fromValue(String value) {
    switch (value) {
      case 'pending':
        return DraftReviewStatus.pending;
      case 'approved':
        return DraftReviewStatus.approved;
      case 'edited':
        return DraftReviewStatus.edited;
      case 'rejected':
        return DraftReviewStatus.rejected;
      default:
        return DraftReviewStatus.pending;
    }
  }

  bool get isApproved =>
      this == DraftReviewStatus.approved || this == DraftReviewStatus.edited;
}

/// Represents a draft flashcard generated by AI in pedagogical format.
///
/// These cards are temporary and need user review before
/// being imported as real cards.
///
/// Pedagogical structure (UC167):
/// - [front]: The question/prompt
/// - [summary]: Short answer (≤240 chars) - main answer shown first
/// - [keyPhrase]: Memory anchor phrase (≤120 chars) - helps memorization
/// - [back]: Full explanation (optional) - for deeper understanding
class AiCardDraft extends Equatable {
  /// Maximum length for summary field.
  static const int maxSummaryLength = 240;

  /// Maximum length for key phrase field.
  static const int maxKeyPhraseLength = 120;

  /// Unique identifier.
  final String id;

  /// ID of the parent AI project.
  final String projectId;

  /// Front side content (question).
  final String front;

  /// Back side content (full explanation).
  final String back;

  /// Short answer/summary (≤240 chars).
  final String? summary;

  /// Memory anchor phrase (≤120 chars).
  final String? keyPhrase;

  /// Optional hint.
  final String? hint;

  /// Tags suggested by AI.
  final List<String> suggestedTags;

  /// Difficulty level suggested by AI.
  final String difficulty;

  /// Current review status.
  final DraftReviewStatus reviewStatus;

  /// Whether this might be a duplicate of existing card.
  final bool isPotentialDuplicate;

  /// ID of similar existing card (if duplicate detected).
  final String? similarCardId;

  /// AI confidence score (0.0 to 1.0).
  final double confidenceScore;

  /// Whether this draft needs human review due to fallback applied (UC168).
  final bool needsReview;

  /// Order index for display.
  final int orderIndex;

  /// When the draft was created.
  final DateTime createdAt;

  /// When the draft was last updated.
  final DateTime updatedAt;

  const AiCardDraft({
    required this.id,
    required this.projectId,
    required this.front,
    required this.back,
    this.summary,
    this.keyPhrase,
    this.hint,
    this.suggestedTags = const [],
    this.difficulty = 'medium',
    this.reviewStatus = DraftReviewStatus.pending,
    this.isPotentialDuplicate = false,
    this.similarCardId,
    this.confidenceScore = 0.8,
    this.needsReview = false,
    this.orderIndex = 0,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Creates a new draft from AI generation.
  factory AiCardDraft.create({
    required String id,
    required String projectId,
    required String front,
    required String back,
    String? summary,
    String? keyPhrase,
    String? hint,
    List<String> suggestedTags = const [],
    String difficulty = 'medium',
    double confidenceScore = 0.8,
    bool needsReview = false,
    int orderIndex = 0,
  }) {
    final now = DateTime.now();
    return AiCardDraft(
      id: id,
      projectId: projectId,
      front: front,
      back: back,
      summary: summary,
      keyPhrase: keyPhrase,
      hint: hint,
      suggestedTags: suggestedTags,
      difficulty: difficulty,
      confidenceScore: confidenceScore,
      needsReview: needsReview,
      orderIndex: orderIndex,
      createdAt: now,
      updatedAt: now,
    );
  }

  /// Returns true if this draft has all pedagogical fields filled.
  bool get hasPedagogicalFields =>
      summary != null &&
      summary!.isNotEmpty &&
      keyPhrase != null &&
      keyPhrase!.isNotEmpty;

  /// Returns the display summary (fallback to first part of back).
  String get displaySummary {
    if (summary != null && summary!.isNotEmpty) {
      return summary!;
    }
    if (back.length <= maxSummaryLength) {
      return back;
    }
    return '${back.substring(0, maxSummaryLength - 3)}...';
  }

  /// Returns the display key phrase (fallback to first sentence).
  String get displayKeyPhrase {
    if (keyPhrase != null && keyPhrase!.isNotEmpty) {
      return keyPhrase!;
    }
    final source = summary ?? back;
    final firstSentence = source.split(RegExp(r'[.!?]')).first.trim();
    if (firstSentence.length <= maxKeyPhraseLength) {
      return firstSentence;
    }
    return '${firstSentence.substring(0, maxKeyPhraseLength - 3)}...';
  }

  /// Whether this draft is approved (including edited).
  bool get isApproved => reviewStatus.isApproved;

  /// Whether this draft is pending review.
  bool get isPending => reviewStatus == DraftReviewStatus.pending;

  /// Whether this draft was rejected.
  bool get isRejected => reviewStatus == DraftReviewStatus.rejected;

  /// Approves the draft as-is.
  AiCardDraft approve() {
    return copyWith(
      reviewStatus: DraftReviewStatus.approved,
      updatedAt: DateTime.now(),
    );
  }

  /// Rejects the draft.
  AiCardDraft reject() {
    return copyWith(
      reviewStatus: DraftReviewStatus.rejected,
      updatedAt: DateTime.now(),
    );
  }

  /// Edits and approves the draft.
  AiCardDraft edit({
    required String front,
    required String back,
    String? summary,
    String? keyPhrase,
    String? hint,
  }) {
    return copyWith(
      front: front,
      back: back,
      summary: summary,
      keyPhrase: keyPhrase,
      hint: hint,
      reviewStatus: DraftReviewStatus.edited,
      needsReview: false, // Editing clears needsReview flag
      updatedAt: DateTime.now(),
    );
  }

  /// Marks as potential duplicate.
  AiCardDraft markAsDuplicate(String similarCardId) {
    return copyWith(
      isPotentialDuplicate: true,
      similarCardId: similarCardId,
      updatedAt: DateTime.now(),
    );
  }

  /// Converts suggested tags JSON string to list.
  static List<String> tagsFromJson(String jsonString) {
    if (jsonString.isEmpty) return [];
    try {
      final list = jsonDecode(jsonString) as List;
      return list.map((e) => e.toString()).toList();
    } catch (_) {
      return [];
    }
  }

  /// Converts tags list to JSON string.
  static String tagsToJson(List<String> tags) {
    return jsonEncode(tags);
  }

  AiCardDraft copyWith({
    String? id,
    String? projectId,
    String? front,
    String? back,
    String? summary,
    String? keyPhrase,
    String? hint,
    List<String>? suggestedTags,
    String? difficulty,
    DraftReviewStatus? reviewStatus,
    bool? isPotentialDuplicate,
    String? similarCardId,
    double? confidenceScore,
    bool? needsReview,
    int? orderIndex,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return AiCardDraft(
      id: id ?? this.id,
      projectId: projectId ?? this.projectId,
      front: front ?? this.front,
      back: back ?? this.back,
      summary: summary ?? this.summary,
      keyPhrase: keyPhrase ?? this.keyPhrase,
      hint: hint ?? this.hint,
      suggestedTags: suggestedTags ?? this.suggestedTags,
      difficulty: difficulty ?? this.difficulty,
      reviewStatus: reviewStatus ?? this.reviewStatus,
      isPotentialDuplicate: isPotentialDuplicate ?? this.isPotentialDuplicate,
      similarCardId: similarCardId ?? this.similarCardId,
      confidenceScore: confidenceScore ?? this.confidenceScore,
      needsReview: needsReview ?? this.needsReview,
      orderIndex: orderIndex ?? this.orderIndex,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  List<Object?> get props => [
        id,
        projectId,
        front,
        back,
        summary,
        keyPhrase,
        hint,
        suggestedTags,
        difficulty,
        reviewStatus,
        isPotentialDuplicate,
        similarCardId,
        confidenceScore,
        needsReview,
        orderIndex,
        createdAt,
        updatedAt,
      ];

  @override
  String toString() =>
      'AiCardDraft(id: $id, front: ${front.length > 20 ? '${front.substring(0, 20)}...' : front}, status: $reviewStatus)';
}
